### PR TITLE
Fileselect

### PR DESCRIPTION
**Pull request by masaguaro**
This is a proposal to use a file select browser to load the training and testing datasets instead of predefining a: **DATASET_PATH** = "/opt/dataiku-dss/config/ipython_notebooks/JCKAGGLEHOUSEPRICES/data/"

I found a code snippet to do the work. I think we can improve. What do you think guys?

### CODE REVIEW

**Comment by neomatrix369** [comment]
@masaguaro did you use the example from the notebook I shared with you?

**Comment by masaguaro** [comment]
I check the notebook you gave me. I was trying to do something similar but I had to many conflicts when installing some libraries. Also,  I think the example that you gave me was for uploading the file for cloud computing. The solution I am proposing it's to choose amongst local files.  What do you think  ?

**Comment by neomatrix369** [comment]
I thought the example could be used (with tweaks) to also work for you use case.

If you got it working, nothing like it,

**Comment by masaguaro** [comment]
We can try to make it work the example you gave me.. probably in one of our sessions ?

**Pull request merged**
